name: deploy

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  deploy-gae:
    runs-on: ubuntu-latest
    
    steps:
      - id: deploy-gae
        uses: google-github-actions/deploy-appengine@v0.4.0
        with:
          credentials: ${{ secrets.gcp_credentials }}
